name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Theos and SDK
      run: |
        echo "Setting up Theos environment..."
        brew install ldid make xz dpkg
        
        # 克隆theos仓库
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        
        # 设置环境变量
        echo "THEOS=$HOME/theos" > ~/.bash_profile
        echo "PATH=$HOME/theos/bin:$PATH" >> ~/.bash_profile
        source ~/.bash_profile
        
        # 下载SDK文件
        echo "Downloading iOS SDK..."
        mkdir -p $HOME/theos/sdks
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip -q master.zip
        
        # 使用cp命令代替mv命令来避免"目录不为空"错误
        cp -R sdks-master/* $HOME/theos/sdks/
        
        # 清理下载的文件
        rm -rf master.zip sdks-master

    - name: Build Project
      run: |
        echo "Building project..."
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        make clean
        make
        make ipa

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FloatingMenu
        path: FloatingMenu.ipa
        retention-days: 7

    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: FloatingMenu.ipa
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
