name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Theos
      run: |
        echo "Setting up Theos environment..."
        brew install ldid make xz dpkg
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" > ~/.bash_profile
        echo "PATH=$HOME/theos/bin:$PATH" >> ~/.bash_profile
        source ~/.bash_profile
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mkdir -p $HOME/theos/sdks
        mv sdks-master/*.sdk $HOME/theos/sdks/
        rm -rf sdks-master master.zip

    - name: Build Project
      run: |
        echo "Building project..."
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        cd iOS-Floating
        make clean
        make
        make ipa

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FloatingMenu
        path: iOS-Floating/FloatingMenu.ipa
        retention-days: 7

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: iOS-Floating/FloatingMenu.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
